assets:
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/

baseurl: /

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/

ga_analytics: UA-XXXXXXXX-X

gems:
  - jekyll-assets
  - jekyll-sitemap

name: cloud.gov.au

permalink: pretty

url: # add site url

global_navigation:
  - Overview: '/overview/'
  - Documentation: 'http://docs.cloud.gov.au'
  - Support: '/support/'
  - Status: 'http://status.cloud.gov.au/'

overview_navigation:
  - Overview: '/overview/'
  - What is cloud.gov.au: '/overview/what-is-cloud/'
  - Why we built it: '/overview/why-we-built-it/'
  - Who can use it: '/overview/who-can-use/'
  - How to use it: '/overview/how-to-use-it/'
  - Projects on cloud.gov.au: '/overview/projects/'
  - Pricing: '/overview/cost/'
  - Security: '/overview/security/'
  - Technology: '/overview/technology/'

support_navigation:
  - Overview: '/support/'
  - Help: '/support/help/'
  - Incident response: '/support/incident-response/'
  - Post incident reports: '/support/incident-reports/'
